name: Dev Build and Release

on:
  workflow_dispatch:
    inputs:
      elfldr_ver:
        description: 'ps5-elfldr version'
        required: true
        default: 'latest'
        type: string
      kexp_ver:
        description: 'ps5-kexp version'
        required: true
        default: 'latest'
        type: string
      pldmgr_ver:
        description: 'ps5-payload-manager version'
        required: true
        default: 'latest'
        type: string

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ISO
        run: ./build_iso.sh --elfldr-ver "${{ inputs.elfldr_ver }}" --kexp-ver "${{ inputs.kexp_ver }}" --pldmgr-ver "${{ inputs.pldmgr_ver }}"

      - name: Get Version
        id: get_version
        run: |
          VERSION=$(make print-version BUILD_TYPE=dev)
          echo "version=${VERSION}-old-kexp" >> $GITHUB_OUTPUT
          ELFLDR_VER=$(basename payloads/poops/src/org/bdj/external/elfldr-ps5-*.elf .elf | sed 's/elfldr-ps5-//')
          KEXP_VER=$(basename payloads/poops/src/org/bdj/external/kexp-*.bin .bin | sed 's/kexp-//')
          PLDMGR_VER=$(basename $(ls ps5_autoloader/pldmgr-*.elf ps5_autoloader/pldmgr_v*.elf 2>/dev/null | head -n 1) .elf | sed -E 's/pldmgr[-_v]+//')
          echo "elfldr_ver=${ELFLDR_VER}" >> $GITHUB_OUTPUT
          echo "kexp_ver=${KEXP_VER}" >> $GITHUB_OUTPUT
          echo "pldmgr_ver=${PLDMGR_VER}" >> $GITHUB_OUTPUT

      - name: Create Dev Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          target_commitish: ${{ github.sha }}
          name: ${{ steps.get_version.outputs.version }}
          prerelease: true
          body: |
            <details>
            <summary>Bundled Binaries</summary>

            This build integrates the following external dependency versions:
            - [itsPLK/ps5-elfldr](https://github.com/itsPLK/ps5-elfldr): [${{ steps.get_version.outputs.elfldr_ver }}](https://github.com/itsPLK/ps5-elfldr/releases/tag/${{ steps.get_version.outputs.elfldr_ver }})
            - [itsPLK/ps5-kexp](https://github.com/itsPLK/ps5-kexp): [${{ steps.get_version.outputs.kexp_ver }}](https://github.com/itsPLK/ps5-kexp/releases/tag/${{ steps.get_version.outputs.kexp_ver }})
            - [itsPLK/ps5-payload-manager](https://github.com/itsPLK/ps5-payload-manager): [v${{ steps.get_version.outputs.pldmgr_ver }}](https://github.com/itsPLK/ps5-payload-manager/releases/tag/v${{ steps.get_version.outputs.pldmgr_ver }})

            </details>
          files: '*.iso'

