name: Stable Build and Release

on:
  workflow_dispatch:
    inputs:
      kexp_ver:
        description: 'ps5-kexp version'
        required: true
        default: 'master'
        type: string

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ISO
        run: ./build_iso.sh --stable --kexp-ver "${{ inputs.kexp_ver }}"

      - name: Get Version
        id: get_version
        run: |
          VERSION=$(make print-version BUILD_TYPE=stable)
          echo "version=${VERSION}-old-kexp" >> $GITHUB_OUTPUT
          TITLE=$(echo "${VERSION}" | cut -d'-' -f1)
          echo "title=${TITLE}-old-kexp" >> $GITHUB_OUTPUT
          ELFLDR_VER=$(basename payloads/poops/src/org/bdj/external/elfldr-ps5-*.elf .elf | sed 's/elfldr-ps5-//')
          KEXP_VER=$(basename payloads/poops/src/org/bdj/external/kexp-*.bin .bin | sed 's/kexp-//')
          AUTOLOADER_VER=$(curl -s https://api.github.com/repos/itsPLK/ps5-unified-autoloader/releases/latest | grep -o '"tag_name": "[^"]*"' | head -n 1 | cut -d'"' -f4)
          echo "elfldr_ver=${ELFLDR_VER}" >> $GITHUB_OUTPUT
          echo "kexp_ver=${KEXP_VER}" >> $GITHUB_OUTPUT
          echo "unified_autoloader_ver=${AUTOLOADER_VER}" >> $GITHUB_OUTPUT

      - name: Create Stable Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          target_commitish: ${{ github.sha }}
          name: ${{ steps.get_version.outputs.title }}
          prerelease: false
          body: |
            <details>
            <summary>Bundled Binaries</summary>

            This build integrates the following external dependency versions:
            - [itsPLK/ps5-elfldr](https://github.com/itsPLK/ps5-elfldr): [${{ steps.get_version.outputs.elfldr_ver }}](https://github.com/itsPLK/ps5-elfldr/releases/tag/${{ steps.get_version.outputs.elfldr_ver }})
            - [itsPLK/ps5-kexp](https://github.com/itsPLK/ps5-kexp): [${{ steps.get_version.outputs.kexp_ver }}](https://github.com/itsPLK/ps5-kexp/releases/tag/${{ steps.get_version.outputs.kexp_ver }})
            - [itsPLK/ps5-unified-autoloader](https://github.com/itsPLK/ps5-unified-autoloader): [${{ steps.get_version.outputs.unified_autoloader_ver }}](https://github.com/itsPLK/ps5-unified-autoloader/releases/tag/${{ steps.get_version.outputs.unified_autoloader_ver }})

            </details>
          files: '*.iso'
